
name: .NET 9 Tests

# تحديد الأحداث التي ستؤدي إلى تشغيل الـ Workflow
on:
  push:
    branches:
      - main  # تشغيل الاختبارات عند الدفع إلى الفرع الرئيسي
  pull_request:
    branches:
      - main  # تشغيل الاختبارات عند تقديم طلب سحب إلى الفرع الرئيسي

jobs:
  build:
    runs-on: ubuntu-latest  # تشغيل على أحدث نسخة من Ubuntu
    strategy:
      matrix:
        dotnet-version: [9.0]  # استخدام الإصدار 9.0 فقط من .NET

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # تحميل الكود من GitHub

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}  # تثبيت الإصدار 9.0 من .NET

    - name: Restore dependencies
      run: dotnet restore  # استعادة الحزم المطلوبة للتطبيق

    - name: Build the application
      run: dotnet build --configuration Release  # بناء الكود في وضع الإصدار (Release)

    - name: Run tests
      run: dotnet test  # تشغيل اختبارات الوحدة
